# labeler 'full' schema

# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:

  'Builds':
    - '\bbuilds:[s]?\b'

  'Wallet'
    - '\bwallet:[s]?\b'

  'Accounts'
    - '\baccounts:[s]?\b'

  'APPS'
    - '\bapps:[s]?\b'

  'Auto'-Builders
    - '\bauto_builders:[s]?\b'


  'Blockchain'
    - '\bblockchain:[s]?\b'

  'Transactions'
    - '\btransactions:[s]?\b'

  'CLI'
    - '\bcli:[s]?\b'

  'Node'
    - '\bnode:[s]?\b'

  'API'
    - '\bapi:[s]?\b'

  'Consensus'
    - '\bconsensus:[s]?\b'

  'Packages'
    - '\bpackages:[s]?\b'

  'Docs'
    - '\bdocs:[s]?\b'

  'Tests'
    - '\btests:[s]?\b'

  'GitHub'
    - '\bgitHub:[s]?\b'

  'Google'
    - '\bgoogle:[s]?\b'

  'GUI'
    - '\bgui:[s]?\b'

  'Licence'
    - '\blicence:[s]?\b'

  'Logging'
    - '\blogging:[s]?\b'

  'Debugging'
    - '\bdebugging:[s]?\b'

  'Release'
    - '\brelease:[s]?\b'

  'Settings'
    - '\bsettings:[s]?\b'

  'libs'
    - '\blibs:[s]?\b'

