changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - restyled-io
  categories:

    - title: Integration
      labels:
        - Integration

    - title: Security
      labels:
        - Security

    - title: Builds
      labels:
        - Builds

    - title: Windows
      labels:
        - Windows

    - title: Linux
      labels:
        - Linux

    - title: Wallet
      labels:
        - Wallet

    - title: Accounts
      labels:
        - Accounts

    - title: Apps
      labels:
        - Apps

    - title: Auto-Builders
      labels:
        - Auto-Builders

    - title: Backup
      labels:
        - Backup

    - title: Blockchain
      labels:
        - Blockchain

    - title: Transactions
      labels:
        - Send
        - Transactions

    - title: CLI
      labels:
        - CLI

    - title: Node
      labels:
        - Node

    - title: API
      labels:
        - API

    - title: Consensus
      labels:
        - Consensus


    - title: Packages
      labels:
        - Packages

    - title: Docs
      labels:
        - Docs

    - title: Tests
      labels:
        - Functional-Tests
        - Stability-Tests
        - Unit-Tests
        - Tests

    - title: GitHub
      labels:
        - GitHub

    - title: Google
      labels:
        - Google-Cloud-Shell

    - title: GUI
      labels:
        - GUI

    - title: Licence
      labels:
        - Licence

    - title: Logging
      labels:
        - Logging

    - title: Debugging
      labels:
        - Debugging

    - title: Release
      labels:
        - Minor
        - Major
        - Release
        - Path

    - title: Performance-Optimization
      labels:
        - Performance-Optimization

    - title: Security
      labels:
        - Security
        - Vulnerability

    - title: Platform
      labels:
        - Windows

    - title: Requirements
      labels:
        - Dependencies

    - title: Research
      labels:
        - Research

    - title: Settings
      labels:
        - Settings

    - title: Status
      labels:
        - Status


    - title: Other Changes
      labels:
        - "*"
