name: Packages Application with Pyinstaller

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-cli-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .
        spec: cli

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: dist/Decentra-Network-CLI
  build-cli-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: cli

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: dist/Decentra-Network-CLI
        