name: Builds

on: 
  push:
    paths:
      - '.github/workflows/builds.yml'
      - 'decentra_network/**'  
      - 'requirements/**'  
      - 'API.spec'
      - 'CLI.spec'
      - 'GUI-win32.spec'
      - 'buildozer.spec'
      - 'recipes/**'

  pull_request:
    paths:
      - '.github/workflows/builds.yml'
      - 'decentra_network/**'  
      - 'requirements/**'
      - 'API.spec'
      - 'CLI.spec'
      - 'GUI-win32.spec'    
      - 'buildozer.spec'
      - 'recipes/**'       
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build-cli-linux:

    runs-on: ubuntu-latest
    environment: Builds       
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: PyInstaller
      run: |
        pyinstaller CLI.spec

    - name: Zip
      run: zip -r cli_linux_${{ github.event.release.tag_name }} dist/Decentra-Network-CLI
    
    - uses: actions/upload-artifact@v2
      with:
        path: cli_linux_${{ github.event.release.tag_name }}.zip
    
    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: 'cli_linux_${{ github.event.release.tag_name }}.zip'

  build-cli-macos:

    runs-on: macos-latest
    environment: Builds       
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: PyInstaller
      run: |
        pyinstaller CLI.spec

    - name: Zip
      run: zip -r cli_macos_${{ github.event.release.tag_name }} dist/Decentra-Network-CLI
    

    - uses: actions/upload-artifact@v2
      with:
        path: cli_macos_${{ github.event.release.tag_name }}.zip


    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: 'cli_macos_${{ github.event.release.tag_name }}.zip'


  build-cli-windows:

    runs-on: windows-latest
    environment: Builds       
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: PyInstaller
      run: |
        pyinstaller CLI.spec

    - name: Zip
      run: zip -r cli_win32_${{ github.event.release.tag_name }} dist/Decentra-Network-CLI
    


    - uses: actions/upload-artifact@v2
      with:
        path: cli_win32_${{ github.event.release.tag_name }}.zip       

    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: 'cli_win32_${{ github.event.release.tag_name }}.zip'


  build-api-linux:

    runs-on: ubuntu-latest
    environment: Builds       
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements/api.txt        
    - name: PyInstaller
      run: |
        pyinstaller API.spec


    - name: Zip
      run: zip -r api_linux_${{ github.event.release.tag_name }} dist/Decentra-Network-API
    

    - uses: actions/upload-artifact@v2
      with:
        path: api_linux_${{ github.event.release.tag_name }}.zip

    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: 'api_linux_${{ github.event.release.tag_name }}.zip'


  build-api-macos:

    runs-on: macos-latest
    environment: Builds       
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements/api.txt        
    - name: PyInstaller
      run: |
        pyinstaller API.spec

    - name: Zip
      run: zip -r api_macos_${{ github.event.release.tag_name }} dist/Decentra-Network-API
    

    - uses: actions/upload-artifact@v2
      with:
        path: api_macos_${{ github.event.release.tag_name }}.zip

    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: 'api_macos_${{ github.event.release.tag_name }}.zip'

  build-api-windows:

    runs-on: windows-latest
    environment: Builds       
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        python -m venv venv
        venv\Scripts\activate.bat
        pip3 install -r requirements/api.txt          
    - name: PyInstaller
      run: |
        pyinstaller API.spec

    - name: Zip
      run: zip -r api_win32_${{ github.event.release.tag_name }} dist/Decentra-Network-API
    

    - uses: actions/upload-artifact@v2
      with:
        path: api_win32_${{ github.event.release.tag_name }}.zip 


    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: 'api_win32_${{ github.event.release.tag_name }}.zip'

  build-gui-windows:

    runs-on: windows-latest
    environment: Builds       
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install pyinstaller==4.10
        pip3 install pyinstaller-hooks-contrib==2022.3 
        python -m venv venv
        venv\Scripts\activate.bat
        pip3 install -r requirements/gui.txt
              
    - name: PyInstaller
      run: |
        $env:KIVY_GL_BACKEND="angle_sdl2"
        pyinstaller GUI-win32.spec

    - name: Zip
      run: zip -r gui_win32_${{ github.event.release.tag_name }} dist/Decentra-Network-GUI
    

    - uses: actions/upload-artifact@v2
      with:
        path: gui_win32_${{ github.event.release.tag_name }}.zip

    - uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: 'gui_win32_${{ github.event.release.tag_name }}.zip'

  build-api-android:
    runs-on: ubuntu-latest
    environment: Builds    
    strategy:
      matrix:
        python-version: [3.8]    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer --profile api android debug

      - name: Zip
        run: zip -r api_android_${{ github.event.release.tag_name }} ${{ steps.buildozer.outputs.filename }} 
      

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: api_android_${{ github.event.release.tag_name }}.zip

      - uses: AButler/upload-release-assets@v2.0
        if: github.event_name == 'release'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}        
          files: 'api_android_${{ github.event.release.tag_name }}.zip'


  build-gui-android:
    runs-on: ubuntu-latest
    environment: Builds    
    strategy:
      matrix:
        python-version: [3.8]    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: 1.4.0
          command: buildozer --profile gui android debug

      - name: Zip
        run: zip -r gui_android_${{ github.event.release.tag_name }} ${{ steps.buildozer.outputs.filename }} 
      

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: gui_android_${{ github.event.release.tag_name }}.zip

      - uses: AButler/upload-release-assets@v2.0
        if: github.event_name == 'release'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}        
          files: 'gui_android_${{ github.event.release.tag_name }}.zip'
