name: Builds

on: 
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build-cli-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: PyInstaller
      run: |
        pyinstaller CLI.spec

    - uses: actions/upload-artifact@v2
      with:
        name: decentra-network-cli-linux
        path: dist/Decentra-Network-CLI
  build-cli-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: PyInstaller
      run: |
        pyinstaller CLI.spec

    - uses: actions/upload-artifact@v2
      with:
        name: decentra-network-cli-win32
        path: dist/Decentra-Network-CLI        

  build-api-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements/api.txt        
    - name: PyInstaller
      run: |
        pyinstaller API.spec

    - uses: actions/upload-artifact@v2
      with:
        name: decentra-network-api-linux
        path: dist/Decentra-Network-API

  build-api-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        python -m venv venv
        venv\Scripts\activate.bat
        pip3 install -r requirements/api.txt          
    - name: PyInstaller
      run: |
        pyinstaller API.spec

    - uses: actions/upload-artifact@v2
      with:
        name: decentra-network-api-win32
        path: dist/Decentra-Network-API  

  build-gui-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install pyinstaller==4.10
        pip3 install pyinstaller-hooks-contrib==2022.3 
        python -m venv venv
        venv\Scripts\activate.bat
        pip3 install -r requirements/gui.txt
              
    - name: PyInstaller
      run: |
        $env:KIVY_GL_BACKEND="angle_sdl2"
        pyinstaller GUI-win32.spec
    - uses: actions/upload-artifact@v2
      with:
        name: decentra-network-gui-win32
        path: dist/Decentra-Network-GUI  
