name: Gource

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  gource:
    runs-on: ubuntu-latest
    environment: Builds   

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          gource_title: 'Decentra Network'
          logo_url: 'https://user-images.githubusercontent.com/41792982/114188349-b7cd0700-9951-11eb-84ea-3b31495b5635.png'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40
          avatars_auto_fetch: true

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: decentra-network-gource
          path: ./gource/gource.mp4
      - name: Zip
        run: zip gource_${{ github.event.release.tag_name }} ./gource/gource.mp4
      - name: Upload the artifacts
        if: github.event_name == 'release'
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ github.event.release.tag_name }}
        with:
          args: 'gource_${{ steps.get_release.tag_name }}.zip'
