name: Labeler
on:
  pull_request:
    paths:
      - '.github/workflows/labeler.yml'
      - '.github/labeler.yml'

jobs:

  labeler:
    runs-on: ubuntu-latest

    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}