name: Tests

on: 
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'docker/**'
      - 'setups/**'
      - 'src/**'  
      - 'requirements/**'
      - 'tests/**'
      - 'auto_builders/**'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'docker/**'
      - 'setups/**'
      - 'src/**'  
      - 'requirements/**'
      - 'tests/**'
      - 'auto_builders/**'      

jobs:
  lint_with_flake8:

    runs-on: ubuntu-latest
    environment: Tests 
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors
        flake8 . --count --select=E9,F63,F7 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  unit-test-ubuntu-latest:
    needs: lint_with_flake8

    runs-on: ubuntu-latest
    environment: Tests 
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements/api.txt
        pip install -r requirements/gui.txt
    - name: Test with pytest
      run: |
        pytest tests/unit_tests
    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: log-report-unit-test-ubuntu-latest
        path: src/logs/*.log      
  
  unit-test-macos-latest:
    needs: lint_with_flake8

    runs-on: macos-latest
    environment: Tests     
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements/api.txt
        pip install -r requirements/gui.txt
    - name: Test with pytest
      run: |
        pytest tests/unit_tests
    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: log-report-unit-test-macos-latest
        path: src/logs/*.log           
  unit-test-windows-latest:
    needs: lint_with_flake8

    runs-on: windows-latest
    environment: Tests     
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements/api.txt
        pip install -r requirements/gui.txt
    - name: Test with pytest
      run: |
        pytest tests/unit_tests
    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: log-report-unit-test-windows-latest
        path: src/logs/*.log           

  functional-test-local-ubuntu-latest:
    needs: [lint_with_flake8, unit-test-ubuntu-latest, unit-test-macos-latest, unit-test-windows-latest]
    runs-on: ubuntu-latest
    environment: Tests 
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and run tests
      run: |
        pip install pytest
        cd ..
        pytest Decentra-Network/tests/functional_tests/local/test_decentra_network_local.py
    - name: Status Information
      run: |
        curl http://localhost:8000/status
        curl http://localhost:8101/status
        curl http://localhost:8102/status
    - name: Archive logs of Node 0
      uses: actions/upload-artifact@v3
      with:
        name: log-report-functional-test-local-ubuntu-latest-node-0
        path: /home/runner/work/Decentra-Network/Decentra-Network-0/src/logs/*.log 
    - name: Archive logs of Node 1
      uses: actions/upload-artifact@v3
      with:
        name: log-report-functional-test-local-ubuntu-latest-node-1
        path: /home/runner/work/Decentra-Network/Decentra-Network-1/src/logs/*.log 
    - name: Archive logs of Node 2
      uses: actions/upload-artifact@v3
      with:
        name: log-report-functional-test-local-ubuntu-latest-node-2
        path: /home/runner/work/Decentra-Network/Decentra-Network-2/src/logs/*.log 

  functional-test-docker-ubuntu-latest:
    needs: [lint_with_flake8, unit-test-ubuntu-latest, unit-test-macos-latest, unit-test-windows-latest]
    runs-on: ubuntu-latest
    environment: Tests 
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and run tests
      run: |
        pip install pytest
        cd ..
        docker build -t ghcr.io/decentra-network/api -f Decentra-Network/docker/local/api/Dockerfile .
        pytest Decentra-Network/tests/functional_tests/docker/test_decentra_network_docker.py
    - name: Status Information
      run: |
        curl http://localhost:8000/status
        curl http://localhost:8101/status
        curl http://localhost:8102/status
    - name: Copy out file from volume
      run: |
        mkdir -p /home/runner/work/Decentra-Network/Decentra-Network-0/src
        mkdir -p /home/runner/work/Decentra-Network/Decentra-Network-1/src
        mkdir -p /home/runner/work/Decentra-Network/Decentra-Network-2/src
        sudo cp -r /var/lib/docker/volumes/decentra-network-logs/_data/  /home/runner/work/Decentra-Network/Decentra-Network-0/src/logs
        sudo cp -r /var/lib/docker/volumes/decentra-network-logs-0/_data/  /home/runner/work/Decentra-Network/Decentra-Network-1/src/logs
        sudo cp -r /var/lib/docker/volumes/decentra-network-logs-1/_data/  /home/runner/work/Decentra-Network/Decentra-Network-2/src/logs
    - name: Archive logs of Node 0
      uses: actions/upload-artifact@v3
      with:
        name: log-report-functional-test-docker-ubuntu-latest-node-0
        path: /home/runner/work/Decentra-Network/Decentra-Network-0/src/logs/*.log 
    - name: Archive logs of Node 1
      uses: actions/upload-artifact@v3
      with:
        name: log-report-functional-test-docker-ubuntu-latest-node-1
        path: /home/runner/work/Decentra-Network/Decentra-Network-1/src/logs/*.log 
    - name: Archive logs of Node 2
      uses: actions/upload-artifact@v3
      with:
        name: log-report-functional-test-docker-ubuntu-latest-node-2
        path: /home/runner/work/Decentra-Network/Decentra-Network-2/src/logs/*.log 


