name: Ubuntu Latest Unit Test

on: [push,pull_request]

jobs:

  build-create-folder:
    name: Building Create Folder
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        cd ..
        cp -r Decentra-Network 2
        cp -r Decentra-Network 3

  build-node-1:
    name: Building The Node 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 Decentra-Network/src/api.py

  build-node-2:
    name: Building The Node 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 2/src/api.py -p 8010

  build-node-3:
    name: Building The Node 3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 3/src/api.py -p 8020

  build_run_test:
    name: Building The Node 3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 Decentra-Network/src/api.py -p 8020
